version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-stretch-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      # install deps
      - run: yarn install --ignore-engines

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.yarn-cache

      - run: npm run test
      - run: npm run test:coverage

      - store_artifacts:
          path: coverage
          prefix: coverage
